# Generated by Django 4.0.3 on 2022-05-25 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vue_app', '0006_alter_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.TextField(max_length=50),
        ),
    ]
