# Generated by Django 4.0.3 on 2022-05-27 01:10

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vue_app', '0008_followerscount'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='post_images')),
                ('profileimg', models.ImageField(default='paw-profile-default.jpg', upload_to='profile_images')),
                ('filename', models.TextField(max_length=20)),
                ('caption', models.TextField(max_length=50)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('no_of_downloaded', models.IntegerField(default=0)),
            ],
        ),
    ]
