# Generated by Django 4.0.3 on 2022-05-27 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vue_app', '0009_postuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='coursename',
            field=models.TextField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='post',
            name='filename',
            field=models.TextField(blank=True, max_length=10),
        ),
    ]
