# Generated by Django 4.0.3 on 2022-06-01 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vue_app', '0011_remove_post_coursename_remove_post_filename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='profileimg',
            field=models.ImageField(default='paw-profile-default.jpg', upload_to='profile_images'),
        ),
    ]
