# Generated by Django 4.0.3 on 2022-06-01 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vue_app', '0012_post_profileimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='profileimg',
        ),
    ]
