# Generated by Django 4.0.3 on 2022-06-02 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vue_app', '0013_remove_post_profileimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='notes',
            field=models.FileField(blank=True, upload_to='post_notefiles'),
        ),
    ]
