# Generated by Django 4.0.3 on 2022-06-02 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vue_app', '0016_alter_post_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=500)),
                ('username', models.CharField(max_length=100)),
            ],
        ),
    ]
